spring:
    profiles:
        active: development
    #konfigurasi jackson
    jackson:
        serialization:
            indent-output: true

    # spring datasource jpa
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./database/boot_swagger?autoReconnect=true
        username: root
        password:
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000

    # spring hibernate
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect